import Searches from "../components/Searches";
import RecipeCard from "../components/RecipeCard";
export default function Recipes() {
    const recipes = [
        {
            title: "Chicken Pizza",
            image: "/img/gallery/chickenPizza.png",
            authorimg: "/img/top-chef/img_1.png",
            description: "Delight in the savory combination of succulent chicken pieces, melted cheese, and a medley of flavorful toppings, all nestled on a crispy pizza crust. Chicken Pizza is a delicious twist on the classic, offering a perfect blend of protein-packed goodness and mouthwatering taste.",
            ingredients_1: "Pizza dough",
            ingredients_2: "Cooked chicken breast, shredded",
            ingredients_3: "Mozzarella cheese, shredded",
            ingredients_4: "Tomato sauce",
            ingredients_5: "Bell peppers, sliced",
            ingredients_6: "Red onions, thinly sliced",
            ingredients_7: "Olive oil",
            ingredients_8: "Italian herbs(oregano, basil)",
            ingredients_9: "Salt and pepper to taste",

            instruction_1: "Preheat the oven to 475°F (245°C).",
            instruction_2: "Roll out the pizza dough on a floured surface.",
            instruction_3: "Spread a layer of tomato sauce on the dough.",
            instruction_4: "Sprinkle shredded mozzarella cheese evenly.",
            instruction_5: "Add shredded chicken, sliced bell peppers, and red onions.",
            instruction_6: "Drizzle with olive oil and sprinkle Italian herbs, salt, and pepper.",
            instruction_7: "Bake in the preheated oven for 12-15 minutes or until the crust is golden."
        },
        {
            title: "Sushi Rolls",
            image: "/img/gallery/roll.png",
            authorimg: "/img/top-chef/img_2.png",
            description: "Indulge in the artful perfection of Sushi Rolls, where expertly crafted rice, fresh seafood, and vegetables come together in a delightful symphony. Each bite offers a burst of flavors, complemented by the subtle tang of soy sauce and the heat of wasabi. Sushi Rolls are a culinary masterpiece that combines taste and aesthetics.",
            ingredients_1: "Sushi Rice",
            ingredients_2: "Nori (seawed) sheets",
            ingredients_3: "Fresh fish (salmon, tuna), thinly sliced",
            ingredients_4: "Avocado sliced",
            ingredients_5: "Cucumber, julienned",
            ingredients_6: "Soy sauce",
            ingredients_7: "Sugar, Rice Vinegar",
            ingredients_8: "Sesame Seeds",
            ingredients_9: "Wasabi",

            instruction_1: "Cook sushi rice according to package instructions. Mix rice vinegar and sugar, fold into the cooked rice, and let it cool.",
            instruction_2: "Place a sheet of nori on a bamboo sushi mat.",
            instruction_3: "Wet your hands and spread a thin layer of sushi rice on the nori, leaving a border at the top.",
            instruction_4: "Arrange slices of fish, avocado, and cucumber on the rice.",
            instruction_5: "Roll the sushi tightly using the bamboo mat.",
            instruction_6: "Slice the roll into bite-sized pieces.",
            instruction_7: "Serve with soy sauce, wasabi, and pickled ginger."
        },
        {
            title: "Cheese Burger",
            image: "/img/gallery/burger.png",
            authorimg: "/img/top-chef/img_3.png",
            description: "Savor the classic appeal of a Cheese Burger – a juicy, grilled patty topped with melted cheese, fresh lettuce, tomatoes, and your favorite condiments, all embraced by a soft, toasted bun. It's a timeless treat that brings together the irresistible flavors of premium beef and creamy cheese.",
            ingredients_1: 'Ground beef',
            ingredients_2: 'Burger buns',
            ingredients_3: 'Cheddar cheese slices',
            ingredients_4: 'Lettuce leaves',
            ingredients_5: 'Tomato slices',
            ingredients_6: 'Pickles',
            ingredients_7: 'Ketchup, Mayonnaise, Mustard',
            ingredients_8: 'Red onion, thinly sliced',
            ingredients_9: 'Salt and pepper to taste',
            instruction_1: 'Form ground beef into patties and season with salt and pepper.',
            instruction_2: 'Grill or pan-fry the patties until cooked to your liking.',
            instruction_3: 'Toast burger buns on the grill or in a pan.',
            instruction_4: 'Assemble the burgers with lettuce, tomato slices, cheese, pickles, and red onion.',
            instruction_5: 'Spread ketchup, mustard, and mayonnaise on the bun.',
            instruction_6: 'Place the cooked patty on the bun.',
            instruction_7: 'Serve your delicious Cheese Burger with your favorite sides!'
        },
        {
            title: "Pizza",
            image: "/img/gallery/Pizza.png",
            authorimg: "/img/top-chef/img_4.png",
            description: "Embark on a culinary journey with the quintessential Pizza – a round canvas of dough adorned with a symphony of ingredients. From the classic Margherita to inventive toppings like pepperoni, mushrooms, and olives, pizza is a versatile delight that caters to diverse taste preferences.",
            ingredients_1: 'Pizza dough',
            ingredients_2: 'Tomato sauce',
            ingredients_3: 'Mozzarella cheese and Parmesan cheese, shredded',
            ingredients_4: 'Pepperoni slices',
            ingredients_5: 'Bell peppers and Fresh basil leaves, sliced',
            ingredients_6: 'Red onions, thinly sliced',
            ingredients_7: 'Olives, sliced',
            ingredients_8: 'Mushrooms, sliced',
            ingredients_9: 'Italian sausage, cooked and crumbled',
            instruction_1: 'Preheat the oven to 475°F (245°C).',
            instruction_2: 'Roll out the pizza dough on a floured surface.',
            instruction_3: 'Spread a layer of tomato sauce on the dough.',
            instruction_4: 'Sprinkle shredded mozzarella cheese evenly.',
            instruction_5: 'Add pepperoni, bell peppers, red onions, olives, mushrooms, and cooked Italian sausage.',
            instruction_6: 'Bake in the preheated oven for 12-15 minutes or until the crust is golden.',
            instruction_7: 'Remove from the oven and sprinkle with fresh basil leaves and grated Parmesan cheese. Slice and enjoy your delicious homemade pizza!'
        },
        {
            title: "Salad",
            image: "/img/gallery/salad.png",
            authorimg: "/img/top-chef/img_5.png",
            description: "Refresh your palate with a vibrant Salad, a harmonious blend of crisp greens, colorful vegetables, and perhaps some protein for added substance. Whether it's a Caesar, Greek, or garden salad, the refreshing crunch and zesty dressings make it a nutritious and delightful choice for a light meal or side dish.",
            ingredients_1: 'Ripe tomatoes, sliced',
            ingredients_2: 'Fresh mozzarella cheese, sliced',
            ingredients_3: 'Fresh basil leaves',
            ingredients_4: 'Balsamic glaze',
            ingredients_5: 'Olive oil',
            ingredients_6: 'Salt and pepper to taste',
            ingredients_7: 'Pine nuts (optional)',
            ingredients_8: 'Baby spinach leaves',
            ingredients_9: 'Red onion, thinly sliced',
            instruction_1: 'Arrange slices of tomatoes and mozzarella on a serving platter.',
            instruction_2: 'Tuck fresh basil leaves between the tomato and cheese slices.',
            instruction_3: 'If using, sprinkle pine nuts over the salad.',
            instruction_4: 'Add baby spinach leaves and thinly sliced red onion.',
            instruction_5: 'Drizzle with balsamic glaze and olive oil.',
            instruction_6: 'Season with salt and pepper to taste.',
            instruction_7: 'Gently toss the salad and serve as a refreshing side or appetizer.',
        },
        {
            title: "Taco",
            image: "/img/gallery/tacos.png",
            authorimg: "/img/top-chef/img_6.png",
            description: "Tacos are a delicious and versatile dish featuring seasoned meat, fresh toppings, and a variety of flavorful sauces. Whether it's beef, chicken, or vegetarian, tacos offer a burst of flavors in every bite!",
            ingredients_1: 'Ground beef or shredded chicken',
            ingredients_2: 'Taco seasoning',
            ingredients_3: 'Taco shells or tortillas',
            ingredients_4: 'Lettuce, shredded',
            ingredients_5: 'Tomatoes, diced',
            ingredients_6: 'Cheese, shredded (cheddar or Mexican blend)',
            ingredients_7: 'Sour cream',
            ingredients_8: 'Salsa',
            ingredients_9: 'Guacamole and Cilantro',
            instruction_1: 'Cook the ground beef or shred the chicken and season with taco seasoning according to package instructions.',
            instruction_2: 'Warm the taco shells or tortillas in a pan or microwave.',
            instruction_3: 'Assemble the tacos by filling each shell with the seasoned meat.',
            instruction_4: 'Top with shredded lettuce, diced tomatoes, shredded cheese, sour cream, salsa, and guacamole.',
            instruction_5: 'Garnish with chopped cilantro if desired.',
            instruction_6: 'Add your favorite garlic and cheese sauce.',
            instruction_7: 'Serve immediately and enjoy your delicious Tacos!',
        },
        {
            title: "Mango Chicken Curry",
            image: "/img/gallery/curry.png",
            authorimg: "/img/top-chef/img_2.png",
            description: "Experience the exotic fusion of sweet and savory in Mango Chicken Curry. Succulent chicken pieces are simmered in a luscious curry sauce enriched with ripe mango puree, coconut milk, and aromatic spices. This dish is a tantalizing journey for your taste buds, bringing together the richness of curry and the fruity sweetness of mango.",
            ingredients_1: 'Chicken pieces',
            ingredients_2: 'Ripe mango, pureed',
            ingredients_3: 'Coconut milk',
            ingredients_4: 'Curry powder',
            ingredients_5: 'Onion, chopped',
            ingredients_6: 'Garlic, minced',
            ingredients_7: 'Ginger, grated',
            ingredients_8: 'Olive oil',
            ingredients_9: 'Cumin and Coriander powder',
            ingredients_11: 'Red chili flakes (optional)',
            instruction_1: 'In a pan, sauté chopped onion, minced garlic, and grated ginger in olive oil.',
            instruction_2: 'Add chicken pieces and brown on all sides.',
            instruction_3: 'Sprinkle cumin powder, coriander powder, and red chili flakes (optional).',
            instruction_4: 'Pour in coconut milk and mango puree.',
            instruction_5: 'Stir in curry powder, salt, and pepper.',
            instruction_6: 'Simmer until the chicken is cooked through and the sauce thickens.',
            instruction_7: 'Serve the Mango Chicken Curry over rice or with naan bread.',
        },
        {
            title: "Spaghetti",
            image: "/img/gallery/Spaghetti.png",
            authorimg: "/img/top-chef/img_1.png",
            description: "Enjoy a quick and flavorful meal with Beef Stir-Fry featuring tender slices of beef, crisp broccoli florets, and vibrant bell peppers. Tossed in a savory soy-based sauce with garlic and ginger, this stir-fry offers a perfect balance of textures and tastes. It's a wholesome and satisfying dish for those craving a savory, Asian-inspired experience.",
            ingredients_1: 'Spaghetti pasta',
            ingredients_2: 'Tomato sauce',
            ingredients_3: 'Ground beef or Italian sausage',
            ingredients_4: 'Garlic, minced',
            ingredients_5: 'Onion, chopped',
            ingredients_6: 'Olive oil',
            ingredients_7: 'Fresh basil leaves',
            ingredients_8: 'Parmesan cheese',
            ingredients_9: 'Alaska s Evaporate Milk',
            instruction_1: 'Cook spaghetti pasta according to package instructions.',
            instruction_2: 'In a pan, sauté minced garlic and chopped onion in olive oil.',
            instruction_3: 'Add ground beef or Italian sausage and cook until browned.',
            instruction_4: 'Pour in tomato sauce and simmer until heated through.',
            instruction_5: 'Add Evaporada milk to add a rich flavour.',
            instruction_6: 'Season with salt and pepper, and stir in fresh basil leaves.',
            instruction_7: 'Serve the sauce over cooked spaghetti and top with grated Parmesan cheese.'
        },
        {
            title: "Beef Stir-Fry with Broccoli",
            image: "/img/gallery/brocolli.png",
            authorimg: "/img/top-chef/img_3.png",
            description: "Savor the classic appeal of a Cheese Burger – a juicy, grilled patty topped with melted cheese, fresh lettuce, tomatoes, and your favorite condiments, all embraced by a soft, toasted bun. It's a timeless treat that brings together the irresistible flavors of premium beef and creamy cheese.",
            ingredients_1: 'Beef strips',
            ingredients_2: 'Broccoli florets',
            ingredients_3: 'Soy sauce',
            ingredients_4: 'Garlic, minced',
            ingredients_5: 'Ginger, grated',
            ingredients_6: 'Sesame oil',
            ingredients_7: 'Olive oil',
            ingredients_8: 'Cornstarch',
            ingredients_9: 'Barbeque Marinate Sauce',
            instruction_1: 'In a bowl, mix soy sauce, minced garlic, grated ginger, sesame oil, and cornstarch.',
            instruction_2: 'Marinate beef strips in the mixture for at least 15 minutes.',
            instruction_3: 'Heat olive oil in a pan and stir-fry marinated beef until browned.',
            instruction_4: 'Add broccoli florets and continue to stir-fry until tender.',
            instruction_5: 'Season with salt and pepper.',
            instruction_6: 'Season with a little bit of salt and pepper.',
            instruction_7: 'Serve the Beef Stir-Fry with rice or noodles.'
        },
        {
            title: "Caprese Salad",
            image: "/img/gallery/Caprese.png",
            authorimg: "/img/top-chef/img_4.png",
            description: "Delight in the simplicity of Caprese Salad, a classic Italian dish that celebrates the harmony of fresh ingredients. Slices of ripe tomatoes, creamy mozzarella cheese, and fragrant basil leaves are drizzled with balsamic glaze and olive oil. Caprese Salad is a refreshing and elegant choice, perfect for those seeking a burst of Mediterranean flavors.",
            ingredients_1: 'Ripe tomatoes, sliced',
            ingredients_2: 'Fresh mozzarella cheese, sliced',
            ingredients_3: 'Fresh basil leaves',
            ingredients_4: 'Balsamic glaze',
            ingredients_5: 'Olive oil',
            ingredients_6: '1 cup balsamic vinegar',
            ingredients_7: 'black pepper, for seasoning',
            ingredients_8: '2 tablespoons honey',
            ingredients_9: 'Extra-virgin olive oil, for drizzling',
            instruction_1: 'Arrange slices of tomatoes and mozzarella on a serving platter.',
            instruction_2: 'Tuck fresh basil leaves between the tomato and cheese slices.',
            instruction_3: 'Drizzle with balsamic glaze and olive oil.',
            instruction_4: 'Season with salt and pepper.',
            instruction_5: 'Add balsamic vinegar and honey to a small saucepan, and stir to combine.',
            instruction_6: 'Arrange tomatoes, mozzarella, and basil leaves, overlapping on a platter.',
            instruction_7: 'Serve as a refreshing side or appetizer.'
        }
    ]
    // .sort(() => Math.random() - 0.5)

    return (
        <div>
            <Searches />
            <div className="recipes-container">
                {recipes.map((recipe, index) => (
                    <RecipeCard key={index} recipe={recipe} />
                ))}
            </div>
        </div>
    )
}